name:                waterfall-cad-examples
version:             0.0.0.1
github:              "joe-warren/opencascade-hs"
license:             LGPL
author:              "Joe Warren"
maintainer:          "josephmarkwarren@gmail.com"
copyright:           "2023 Joe Warren"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            Examples for Waterfall CAD, a Declarative CAD/Solid Modeling Library
category:            Graphics
description:         Please see the README on GitHub at <https://github.com/joe-warren/opencascade-hs#readme>

dependencies:
- base >= 4.7 && < 5
- opencascade-hs ^>=0.0.0.1
- waterfall-cad ^>=0.0.0.1
- linear >= 1.21 && < 2
- lens >= 5 && < 6
- optparse-applicative >= 0.17 && < 0.19

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  waterfall-cad-examples:
    main:                Main.hs
    dependencies: 
      waterfall-cad-examples
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

library:
  source-dirs: src
